task: pickup
true_agent:
  preference:
    - reward_carry_object_hof: 1
  skill:
    - left
    - right
    - forward
    - pickup
    - drop
    - toggle
    - done
  env:
    task: pickup
    layout: room_door_key
    edits: [double_grid_size, flip_vertical, change_target_color, hide_target_in_box, change_agent_view_size, add_opening, toggle_opening, block_opening, hide_tool_in_box, toggle_opening]
    seed: 35
    allowed_object_colors: ["green", "blue"]
false_agent:
  preference:
    - reward_carry_object_hof: 1
  skill:
    - left
    - right
    - forward
    - pickup
    - drop
    - toggle
    - done
  env:
    task: pickup
    layout: treasure_island
    edits: [double_grid_size, flip_vertical, change_target_color, hide_target_in_box, change_agent_view_size, add_opening, toggle_opening, add_passage, block_opening, put_agent_inside_section, hide_tool_in_box]
    seed: 1233
    allowed_object_colors: ["green", "blue"]

