principal:
  query_source: scale
  model_source: mistral
  basic_reward_functions:
    - { name: "reward_reach_object_hof" }
  basic_reward_weights:
    - 1
  skills:
    - turn_left
    - turn_right
    - forward
    - pickup
    - drop
    - toggle
    - move_forward_1_steps
    - move_forward_2_steps
    - move_forward_3_steps
    - move_forward_4_steps
    - move_forward_5_steps
    - move_forward_6_steps
    - move_forward_7_steps
    - move_forward_8_steps
    - move_forward_9_steps
    - move_left_1_steps
    - move_left_2_steps
    - move_left_3_steps
    - move_left_4_steps
    - move_left_5_steps
    - move_left_6_steps
    - move_left_7_steps
    - move_left_8_steps
    - move_left_9_steps
    - move_right_1_steps
    - move_right_2_steps
    - move_right_3_steps
    - move_right_4_steps
    - move_right_5_steps
    - move_right_6_steps
    - move_right_7_steps
    - move_right_8_steps
    - move_right_9_steps
    - move_backward_1_steps
    - move_backward_2_steps
    - move_backward_3_steps
    - move_backward_4_steps
    - move_backward_5_steps
    - move_backward_6_steps
    - move_backward_7_steps
    - move_backward_8_steps
    - move_backward_9_steps
    - go_to_red_goal
    - go_to_red_ball
    - go_to_red_box
    - go_to_red_key
    - go_to_red_door
    - go_to_yellow_goal
    - go_to_yellow_ball
    - go_to_yellow_box
    - go_to_yellow_key
    - go_to_yellow_door
    - go_to_green_goal
    - go_to_green_ball
    - go_to_green_box
    - go_to_green_key
    - go_to_green_door
    - go_to_blue_goal
    - go_to_blue_ball
    - go_to_blue_box
    - go_to_blue_key
    - go_to_blue_door
    - go_to_purple_goal
    - go_to_purple_ball
    - go_to_purple_box
    - go_to_purple_key
    - go_to_purple_door
    - go_to_wall
    - go_to_lava
    - pickup_red_ball
    - pickup_red_box
    - pickup_red_key
    - pickup_yellow_ball
    - pickup_yellow_box
    - pickup_yellow_key
    - pickup_green_ball
    - pickup_green_box
    - pickup_green_key
    - pickup_blue_ball
    - pickup_blue_box
    - pickup_blue_key
    - pickup_purple_ball
    - pickup_purple_box
    - pickup_purple_key
    - put_down_red_ball
    - put_down_red_box
    - put_down_red_key
    - put_down_yellow_ball
    - put_down_yellow_box
    - put_down_yellow_key
    - put_down_green_ball
    - put_down_green_box
    - put_down_green_key
    - put_down_blue_ball
    - put_down_blue_box
    - put_down_blue_key
    - put_down_purple_ball
    - put_down_purple_box
    - put_down_purple_key
    - open_red_door
    - open_red_box
    - open_yellow_door
    - open_yellow_box
    - open_green_door
    - open_green_box
    - open_blue_door
    - open_blue_box
    - open_purple_door
    - open_purple_box
    - unlock_red_door
    - unlock_yellow_door
    - unlock_green_door
    - unlock_blue_door
    - unlock_purple_door
    - close_red_door
    - close_yellow_door
    - close_green_door
    - close_blue_door
    - close_purple_door

attendant:
  query_source: scale
  model_source: mistral
  basic_reward_functions:
    - { name: "reward_reach_object_hof" }
  basic_reward_weights:
    - 1
  skills:
    - turn_left
    - turn_right
    - forward
    - pickup
    - drop
    - toggle
    - move_forward_1_steps
    - move_forward_2_steps
    - move_forward_3_steps
    - move_forward_4_steps
    - move_forward_5_steps
    - move_forward_6_steps
    - move_forward_7_steps
    - move_forward_8_steps
    - move_forward_9_steps
    - move_left_1_steps
    - move_left_2_steps
    - move_left_3_steps
    - move_left_4_steps
    - move_left_5_steps
    - move_left_6_steps
    - move_left_7_steps
    - move_left_8_steps
    - move_left_9_steps
    - move_right_1_steps
    - move_right_2_steps
    - move_right_3_steps
    - move_right_4_steps
    - move_right_5_steps
    - move_right_6_steps
    - move_right_7_steps
    - move_right_8_steps
    - move_right_9_steps
    - move_backward_1_steps
    - move_backward_2_steps
    - move_backward_3_steps
    - move_backward_4_steps
    - move_backward_5_steps
    - move_backward_6_steps
    - move_backward_7_steps
    - move_backward_8_steps
    - move_backward_9_steps
    - go_to_red_goal
    - go_to_red_ball
    - go_to_red_box
    - go_to_red_key
    - go_to_red_door
    - go_to_yellow_goal
    - go_to_yellow_ball
    - go_to_yellow_box
    - go_to_yellow_key
    - go_to_yellow_door
    - go_to_green_goal
    - go_to_green_ball
    - go_to_green_box
    - go_to_green_key
    - go_to_green_door
    - go_to_blue_goal
    - go_to_blue_ball
    - go_to_blue_box
    - go_to_blue_key
    - go_to_blue_door
    - go_to_purple_goal
    - go_to_purple_ball
    - go_to_purple_box
    - go_to_purple_key
    - go_to_purple_door
    - go_to_wall
    - go_to_lava
    - pickup_red_ball
    - pickup_red_box
    - pickup_red_key
    - pickup_yellow_ball
    - pickup_yellow_box
    - pickup_yellow_key
    - pickup_green_ball
    - pickup_green_box
    - pickup_green_key
    - pickup_blue_ball
    - pickup_blue_box
    - pickup_blue_key
    - pickup_purple_ball
    - pickup_purple_box
    - pickup_purple_key
    - put_down_red_ball
    - put_down_red_box
    - put_down_red_key
    - put_down_yellow_ball
    - put_down_yellow_box
    - put_down_yellow_key
    - put_down_green_ball
    - put_down_green_box
    - put_down_green_key
    - put_down_blue_ball
    - put_down_blue_box
    - put_down_blue_key
    - put_down_purple_ball
    - put_down_purple_box
    - put_down_purple_key
    - open_red_door
    - open_red_box
    - open_yellow_door
    - open_yellow_box
    - open_green_door
    - open_green_box
    - open_blue_door
    - open_blue_box
    - open_purple_door
    - open_purple_box
    - unlock_red_door
    - unlock_yellow_door
    - unlock_green_door
    - unlock_blue_door
    - unlock_purple_door
    - close_red_door
    - close_yellow_door
    - close_green_door
    - close_blue_door
    - close_purple_door

env_specs:
  task: GOTO
  principal_level: EMPTY
  attendant_level: DEATH
  seed: 168
  attendant_variants: [OBJECTS]
  principal_render_mode: human
  attendant_render_mode: human